apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v1.14.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:v1.14.0
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-dynamodb
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-dynamodb:v1.13.1
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apigatewayv2
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apigatewayv2:v1.13.1
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:v1.13.1
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v1.13.1
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-lambda
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-lambda:v1.13.0
  runtimeConfigRef:
    name: aws-irsa-drc
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:v1.13.1
  runtimeConfigRef:
    name: aws-irsa-drc