apiVersion: v1
kind: Secret
metadata:
  name: backstage-env-vars
  namespace: backstage
stringData:
  BACKSTAGE_FRONTEND_URL: https://${DOMAIN_NAME}
  POSTGRES_HOST: postgresql.backstage.svc.cluster.local
  POSTGRES_PORT: '5432'
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  ARGO_WORKFLOWS_URL: https://${DOMAIN_NAME}/argo-workflows/
  KEYCLOAK_NAME_METADATA: https://${DOMAIN_NAME}/keycloak/realms/cnoe/.well-known/openid-configuration
  KEYCLOAK_CLIENT_SECRET: '${CLIENT_SECRET}'
  ARGOCD_AUTH_TOKEN: 'argocd.token=${argocdToken}'
  ARGO_CD_URL: 'https://argocd-server.argocd.svc.cluster.local/api/v1/'
  GITEA_BASE_URL: https://${DOMAIN_NAME}/gitea
  GITEA_HOST: '${DOMAIN_NAME}'
  DOMAIN_NAME: '${DOMAIN_NAME}'
  GITEA_USERNAME: giteaAdmin
  GITEA_PASSWORD: mysecretgiteapassword!

