# This is the GITHUB URL where Kubernetes manifests are stored.
# If you forked this repo, you will need to update this.
repo_url: "https://github.com/elamaran11/cnoe-appmod-implementation"
# Tags to apply to AWS resources
tags: 
  env: "dev"
  project: "modern-engg"
region: "us-west-2"
# The name of the EKS cluster you are installing this under.
cluster_name: "modern-engineering"

# If using external DNS, specify the Route53 hosted zone ID. Required if enable_dns_management is set to true
#hosted_zone_id: Z03804463VDEET6154SUK
# if external DNS is not used, this value must be provided.
domain_name: INGRESS_DNS

# If set to true, we will store secrets to AWS Secrets Manager, then sync it to the cluster using External Secrets Operator.
enable_external_secret: true

# If set to true will apply flux and tofu manifests to allow deploying terraform resources from backstage.
enable_terraform_integrations: true

# If set to true will apply spark and ray operators to allow deploying of aiml applications from backstage.
enable_aiml_integrations: true
