apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  namespace: airflow
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sleep", "infinity"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: airflow-efs-claim
