apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak.conf: |
    # Database
    # The database vendor.
    db=postgres

    # The username of the database user.
    db-username=keycloak
    db-url-host=postgresql.keycloak

    # Observability

    # If the server should expose healthcheck endpoints.
    #health-enabled=true

    # If the server should expose metrics endpoints.
    #metrics-enabled=true

    # The proxy address forwarding mode if the server is behind a reverse proxy.
    proxy=edge

    # this should only be allowed in development. NEVER in production.
    hostname-strict=false
    hostname-strict-backchannel=false
    http-relative-path=keycloak
