apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
  namespace: kube-system
spec:
  serviceAccountName: efs-csi-controller-sa
  containers:
  - name: sleep-container
    image: amazon/aws-cli
    command: ["/bin/sleep", "infinity"]
    #command: ["/bin/sh", "-c"]
    #args: ["while true; do sleep 30; done"]
