apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  source:
    repoURL: ${GITHUB_URL}
    targetRevision: main
    path: "Chapter 8/packages/crossplane/dev/"
    parameters:
      - name: ROLE_ARN
        value: ${ROLE_ARN}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions: []
