apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  source:
    repoURL: ${GITHUB_URL}
    targetRevision: HEAD
    path: "Chapter 8/packages/crossplane-compositions/dev/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated: {}
    syncOptions: []
