apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: webserver
          image: nginx:1.24.0-alpine
          ports:
          - containerPort: 80 
        - name: sidecar-container
          image: quay.io/curl/curl:8.6.0
          command: ["/bin/sleep", "infinity"]
