workflow:
  serviceAccount:
    create: false
  rbac:
    create: false
server:
  baseHref: /argo-workflows/
  sso:
    insecureSkipVerify: true
    enabled: true
    clientId:
      name: keycloak-oidc
      key: client-id
    clientSecret:
      name: keycloak-oidc
      key: secret-key
    scopes:
      - openid
      - profile
      - email
      - groups
    rbac:
      enabled: true
    nodeEvents:
      enabled: false
  extraArgs:
    - --auth-mode=client
    - --auth-mode=sso
