apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: kubeflow/pytorch-dist-mnist:v1-736c814
              #command: ["/bin/sleep", "infinity"]
              command: ["python", "-u", "/opt/mnist/src/mnist.py"]
              args: ["--backend", "nccl", "--dir", "/mnt/pytorch/model"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
              - mountPath: /mnt/pytorch
                name: training
                subPath: pytorch
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: kubelow-efs-shared
                readOnly: false
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers: 
            - name: pytorch
              image: kubeflow/pytorch-dist-mnist:v1-736c814
              command: ["python", "/opt/mnist/src/mnist.py"]
              args: ["--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
